#SPDX-License-Identifier: MIT-0
---
# tasks file for dnsdist
- name: Install dnsdist and deps
  package:
    name: "{{ item }}"
    state: present
  loop:
    - cron
    - dnsdist
    - python3-lmdb
    - liblmdb-dev
    - liblmdb0
  become: true

- name: Template scripts
  template:
    src: "{{ item }}.j2"
    dest: "{{ dnsdist_etc_dir }}/{{ item }}"
    owner: root
    group: root
    mode: "0750"
    lstrip_blocks: yes
  loop:
    - "blocklist_fetch.sh"
    - "blocklist_update.sh"
    - "lmdb_create.py"
  become: true

- name: Upload custom blocklist
  template:
    src: "{{ lookup('first_found', dnsdist_custom_txt) }}"
    dest: "{{ dnsdist_etc_dir }}/lists/custom.txt"
    owner: root
    group: root
    mode: "0644"
    lstrip_blocks: yes
  vars:
    dnsdist_custom_txt:
      files:
        - "custom.txt.j2"
      paths:
        - "{{ playbook_dir }}/templates/{{ ansible_facts['hostname'] }}"
        - "{{ playbook_dir }}/templates"
        - "{{ role_path }}/templates"
  become: true

- name: Upload allowlist
  template:
    src: "{{ lookup('first_found', dnsdist_allowlist_txt) }}"
    dest: "{{ dnsdist_etc_dir }}/allowlist.txt"
    owner: root
    group: root
    mode: "0644"
    lstrip_blocks: yes
  vars:
    dnsdist_allowlist_txt:
      files:
        - "allowlist.txt.j2"
      paths:
        - "{{ playbook_dir }}/templates/{{ ansible_facts['hostname'] }}"
        - "{{ playbook_dir }}/templates"
        - "{{ role_path }}/templates"
  become: true

- name: Template dnsdist config, defaulting to the role's template last
  template:
    src: "{{ lookup('first_found', params) }}"
    dest: "{{ dnsdist_etc_dir }}/dnsdist.conf"
    owner: root
    group: _dnsdist
    mode: "0640"
    lstrip_blocks: yes
  vars:
    params:
      files:
        - dnsdist.conf.j2
      paths:
        - "{{ playbook_dir }}/templates/{{ ansible_facts['hostname'] }}"
        - "{{ playbook_dir }}/templates"
        - "{{ role_path }}/templates"
  become: true
  notify:
    - check dnsdist config
    - restart dnsdist

- name: Check if {{ dnsdist_lmdb_name }} already exists
  stat:
    path: "{{ dnsdist_etc_dir }}/{{ dnsdist_lmdb_name }}"
  register: dnsdist_lmdb_exists

- name: Run blocklist creation
  command: "{{ dnsdist_etc_dir }}/blocklist_update.sh"
  become: true
  when: dnsdist_lmdb_exists.stat.isdir is not defined

- name: Ensure cron task for updating dnsdist exists
  ansible.builtin.cron:
    name: "dnsdist blocklist update"
    job: "{{ dnsdist_etc_dir }}/blocklist_update.sh"
    user: root
    minute: 07
    hour: 04
  become: true

